package com.richenterprises.banking_api.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * The bank account entity.
 * This will map to the 'accounts' table in PostgreSQL.
 * The balance is stored in integer cents (never floating point values).
 */
@Entity
@Table(name = "accounts")
@Getter
@Setter
@NoArgsConstructor 
@AllArgsConstructor 
@Builder 
public class Account {

    /**
     * The Primary key. This uses PostgreSQL's BIGSERIAL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * The user who owns this account. 
     * Many accounts can belong to one user. 
     * LAZY fetch means the user data is loaded only when accessed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The unique account number. (Generated by the service layer).
     */
    @Column(unique = true, nullable = false)
    private String accountNumber;

    /**
     * The CHECKING or SAVINGS. (Stored as a string in the database).
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AccountType type;

    /**
     * The balance in integer cents. ($100.50 is stored as 10050).
     */
    @Column(nullable = false)
    @Builder.Default
    private Long balance = 0L;

    /**
     * The account status is ACTIVE or FROZEN. 
     * The default is ACTIVE. 
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private AccountStatus status = AccountStatus.ACTIVE;

    /**
     * The timestamp set automatically on creation. (Immutable after insert).
     */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;
    
}
