spring.application.name=banking-api

# JDBC connection string pointing to the Docker container on port 5432.
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db

# username and password which match the credentials in the docker-compose.yml file.
spring.datasource.username=banking_user
spring.datasource.password=banking_pass

#driver-class-name tells Spring Boot to use the PostgreSQL driver.
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate checks that your Java entities match the database schema but it will not
# create or drop tables automatically. The schema will be controlled manually.
spring.jpa.hibernate.ddl-auto=validate

# This prevents the database queries from running during view rendering, which is a hidden
# performance trap in REST APIs.
spring.jpa.open-in-view=false

# This tells Spring Boot to read 'jwt.secret' from an environment variable called JWT.SECRET.
# If the variable is missing, use the default string.
jwt.secret=${JWT_SECRET:default-dev-secret-do-not-use-in-production}
jwt.expiration=900000
